client:
  secret:
    path: ${CLIENT_SECRET_PATH}
  credential:
    path: ${STORED_CREDENTIAL_PATH}

spring:
  application:
    name: Pupcycle Wix Order Handler
  profiles:
    active: default

server:
  port: 8091

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: ERROR

history:
  path: ${HISTORY_PATH}