client:
  secret:
    path: ${CLIENT_SECRET_PATH}
  credential:
    path: ${STORED_CREDENTIAL_PATH}

spring:
  application:
    name: Pupcycle Wix Order Handler
  profiles:
    active: default

server:
  port: 8091

logging:
  level:
    org.springframework.web: INFO
    org.hibernate: ERROR

history:
  path: ${HISTORY_PATH}

filter:
  expected-sender: contact@pupcycle.org
  expected-subject: NICE! YOU JUST GOT AN ORDER

spreadsheet:
  id: ${SPREADSHEET_ID}
  name: ${SPREADSHEET_NAME}